name: 筛选地区

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run CFTest
        run: |
          python CFTest.py -d HKG -o HKG -i 10
          python CFTest.py -d KHH -o KHH -i 5 
          python CFTest.py -d SIN -o SIN -i 5 
          python CFTest.py -d NRT -o NRT -i 5 
          python CFTest.py -d SEA -o SEA -i 5 
      
      - name: Merge
        run: |
          python merge.py
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 地区测试
          path: ips.txt