name: 筛选地区

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run CFTest
        run: |
          python CFTest.py HKG 10 HKG.txt
          python CFTest.py KHH 5 KHH.txt
          python CFTest.py SIN 5 SIN.txt
          python CFTest.py NRT 5 NRT.txt
          python CFTest.py SEA 5 SEA.txt
      
      - name: Merge
        run: |
          python merge.py
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 地区测试
          path: ips.txt